VKart/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VKart.Models;

namespace VKart.Controllers
{
    public class FormController : Controller
    {

        public ActionResult Upload()
        {
            ViewBag.Message = string.Empty;
            return View();
        }

        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase postedFile, string fileKey)
        {
            if (postedFile != null)
            {
                string path = Server.MapPath("~/Uploads/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                var uploadedFileOriginalName = Path.GetFileName(postedFile.FileName);

                postedFile.SaveAs(path + fileKey + Path.GetExtension(postedFile.FileName));

                ViewBag.Message = "File uploaded successfully.";
            }

            return View("Upload");
        }

        public ActionResult ReadImagesFromDirectory()
        {
            List<FileDetails> files = new List<FileDetails>();

            string path = Server.MapPath("~/Uploads/");


            foreach (var item in Directory.GetFiles(path))
            {
                files.Add(new FileDetails
                {
                    Name = Path.GetFileNameWithoutExtension(item),
                    Path = Url.Content(string.Format("~/Uploads/{0}", Path.GetFileName(item)))
                });
            }


            return View(files.AsEnumerable());
        }

    }
}

VKart/Views/Form/ReadImagesFromDirectory.cshtml
@using VKart.Models

@model IEnumerable<FileDetails>

@{
    ViewBag.Title = "Gallery";
}
    <div class="container">
        <div class=" row header">
            <p>List all the Images of the Upload Folder</p>
        </div>
        <div class="row">
            @{
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>File Name</th>
                            <th>Image</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (FileDetails item in Model)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td><img src="@item.Path" style="max-height: 300px;max-width:800px"></td>
                            </tr>
                        }

                    </tbody>
                </table>

            }
        </div>
    </div>

    <style>
        
        .header {
            
            text-align: center;
             font-family: Arial;
            color: blueviolet;
            font-size: 30px;
        }

    </style>

VKart/Views/Form/Upload.cshtml

@{
    ViewBag.Title = "Upload Files";
}

    <div>
        @using (Html.BeginForm("UploadFile", "Form", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <div class="form-group row">
                <label for="fileKey" class="col-sm-2 col-form-label">File Name:</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="fileKey" placeholder="File Key">
                </div>
            </div>
            <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 col-form-label">Select File:</label>
                <div class="col-sm-10">
                    <input type="file" class="form-control" name="postedFile" accept=".png,.jpg">
                </div>
            </div>

            <hr />
            <input type="submit" value="Upload" class="btn btn-primary" />
            <br />
            <span style="color:green">@ViewBag.Message</span>
        }


    </div>
