VKart/Controllers/ExamplesController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VKart.Models;

namespace VKart.Controllers
{
    public class ExamplesController : Controller
    {
      
        public ActionResult General()
        {
            return View();
        }

        private List<Role> LoadRoles(string userName)
        {
            var roles = new List<Role>();
           
            roles.Add(new Role() { RoleId = 1 ,RoleName = "Admin" });
            roles.Add(new Role() { RoleId = 2, RoleName = "Manager" });
            roles.Add(new Role() { RoleId = 3, RoleName = "Supervisior" });
            roles.Add(new Role() { RoleId = 3, RoleName = "Guest" });

            return roles;
        }

        [AllowAnonymous]
        public ActionResult GetRolesByUsername(string userName)
        {
            string results = string.Empty;

            if (!string.IsNullOrEmpty(userName))
            {
                SelectListItem[] items;
                var roles = LoadRoles(userName);
                items = roles.Select(role => new SelectListItem
                {
                    Text = role.RoleName,
                    Value = role.RoleId.ToString()
                }).ToArray();

                results = JsonConvert.SerializeObject(items);
            }
            return Json(results, JsonRequestBehavior.AllowGet);
        }
    }
}

VKart/Views/Examples/General.cshtml
@model VKart.Models.User
@{
    ViewBag.Title = "General";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <section class="content">
        @using (Html.BeginForm("General", "Examples", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { id = "GeneralExampleForm" }))
        {
            <div class="row">
                <div class="col-md-6">
                    <div class="box box-danger">
                        <div class="box-header">
                            <h3 class="box-title">General Examples information</h3>
                        </div>
                        <div class="form-horizontal">
                            <div class="box-body">


                                <div class="form-group">
                                    @*@Html.LabelFor(x => x.UserName, new { @class = "col-sm-4 control-label" })*@
                                    <div class="col-sm-8">
                                        @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(x => x.Roles, new { @class = "col-sm-4 control-label" })
                                    <div class="col-sm-8">
                                        @Html.DropDownListFor(x => x.Roles, new SelectList(Enumerable.Empty<SelectListItem>(), "Value", "Text"), "- Select Role -", new { @class = "form-control" })
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="box box-danger">
                        <div class="form-horizontal">
                            <div class="box-body">
                                <div class="form-group">
                                    @Html.LabelFor(x => x.UserName, new { @class = "col-sm-4 control-label" })
                                    <div class="col-sm-8">
                                        @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(x => x.Roles, new { @class = "col-sm-4 control-label" })
                                    <div class="col-sm-8">
                                        @Html.DropDownListFor(x => x.Roles, new SelectList(Enumerable.Empty<SelectListItem>(), "Value", "Text"), "- Select Role -", new { @class = "form-control" })
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="box-header">
                    <div class="box box-primary">
                        <div class="box-footer">
                            <button id="savebtn" type="submit" name="action:Save" value="Save" class="btn btn-danger">Save</button>
                            <button id="submitbtn" type="submit" name="action:Submit" value="Submit" class="btn btn-danger">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        }

    </section>
</div>

<script type="text/javascript">
        

            $("#UserName").change(function () {
                LoadRoles();
            });

            function LoadRoles() {
                var username = $('#UserName').val();
                $.ajax({
                    url: '/Examples/GetRolesByUsername',
                    type: "GET",
                    dataType: "JSON",
                    data: { userName: username },
                    beforeSend: function (xhr) {
                        
                    },
                    success: function (results) {
                        $("#Roles").html(""); // clear before appending new list
                        $.each($.parseJSON(results), function (index, data) {
                            $("#Roles").append($('<option></option>').val(data.Value).html(data.Text));
                        });
                        
                    },
                    error: function (xhr, status, error) {
                        
                    }
                });
            }
       
</script>